[package]
name = "readerwriter"
version = "0.1.0"
authors = ["Oleg Andreev <oleganza@gmail.com>"]
edition = "2018"

[dependencies]
merlin = {version = "2.0", optional = true }
bytes = {version = "0.5.4", optional = true }
